### PR TITLE
Remove StreamQuery from API Playground

### PR DESCRIPTION
**Pull request by pwoznic**
Modified the OAS and sidebar to remove stream-query. The process I followed was running the job in bitbucket (thank you Shane), running the openapispec-gen script in Docker, and then I took the changes from this script and modified the yaml and js.

### CODE REVIEW

**Comment by pwoznic** [comment]
I left this PR in draft because I want to ensure that I followed the correct process.

**Comment by pwoznic** [comment]
This change is manual based on the discussion this morning. When I made the changes the error went away and the doc site was able to build

**Comment by eskibars** [comment]
Thanks!  LGTM!

**Review by eskibars — APPROVED** [review]

**Review by eskibars — CHANGES_REQUESTED** [review]
Just realized 1 small issue: you added .DS_Store.  Please remove that file.  Other than that, LGTM

**Review by pwoznic — COMMENTED** [review]
Removed .DS_Store

**Pull request merged**
