### PR TITLE
Add direct GA integration.

### PR DESCRIPTION
**Pull request by cjcenizal**
Changes based on these references:
* https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-google-gtag
* https://github.com/facebook/docusaurus/issues/7221#issuecomment-1140464274

### CODE REVIEW

**Review by eskibars — APPROVED** [review]
LGTM, thanks

**Comment by eskibars** [comment]
@cjcenizal it sounded like this can/should be closed, but I wanted to confirm before doing so

**Comment by cjcenizal** [comment]
Thanks for the ping @eskibars! Can we keep this open a bit longer please? I can take ownership for closing this when we're done with it if that makes things easier for you.

**Comment by eskibars** [comment]
Yep, no worries @cjcenizal .  Just wanted to ensure we didn't have long standing open PRs.  Take your time

**Pull request closed without merging**
