### PR TITLE
Align CSS with VUI

### PR DESCRIPTION
**Pull request by cjcenizal**
# Screenshots

## Light mode

image

image

image

image

## Dark mode

image

image

image

image

### CODE REVIEW

**Comment by cjcenizal** [comment]
CC @eskibars @danielone Still a work in progress, just giving you a head's up. Feedback welcome!

**Comment by cjcenizal** [comment]
@eskibars @danielone @pwoznic This is ready for review!

**Comment by cjcenizal** [comment]
Note that the styles have evolved past the point at which the screenshots were taken. To see the latest changes please run this branch locally.

**Review by pwoznic — APPROVED** [review]
I love this redesign, specifically the fonts and the light/dark theme toggle! The dark theme really brings out the contrast of the code blocks. I also really like the TOC because there is less white space in between the headings so there is less scrolling.

**Comment by cjcenizal** [comment]
This change is cosmetic so I'm going to merge it. It will be trivial to revert this change if we need to.

**Pull request merged**
